// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/ci-flakes": {
    params: {};
  };
  "/issues": {
    params: {};
  };
  "/prs": {
    params: {};
  };
  "/issue-chart": {
    params: {};
  };
  "/bus-factor": {
    params: {};
  };
  "/issue-triage": {
    params: {};
  };
  "/pr-health": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/ci-flakes" | "/issues" | "/prs" | "/issue-chart" | "/bus-factor" | "/issue-triage" | "/pr-health";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/ci-flakes" | "/issues" | "/prs" | "/issue-chart" | "/bus-factor" | "/issue-triage" | "/pr-health";
  };
  "routes/ci-flakes.tsx": {
    id: "routes/ci-flakes";
    page: "/ci-flakes";
  };
  "routes/issues.tsx": {
    id: "routes/issues";
    page: "/issues";
  };
  "routes/prs.tsx": {
    id: "routes/prs";
    page: "/prs";
  };
  "routes/issue-chart.tsx": {
    id: "routes/issue-chart";
    page: "/issue-chart";
  };
  "routes/bus-factor.tsx": {
    id: "routes/bus-factor";
    page: "/bus-factor";
  };
  "routes/issue-triage.tsx": {
    id: "routes/issue-triage";
    page: "/issue-triage";
  };
  "routes/pr-health.tsx": {
    id: "routes/pr-health";
    page: "/pr-health";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/ci-flakes": typeof import("./app/routes/ci-flakes.tsx");
  "routes/issues": typeof import("./app/routes/issues.tsx");
  "routes/prs": typeof import("./app/routes/prs.tsx");
  "routes/issue-chart": typeof import("./app/routes/issue-chart.tsx");
  "routes/bus-factor": typeof import("./app/routes/bus-factor.tsx");
  "routes/issue-triage": typeof import("./app/routes/issue-triage.tsx");
  "routes/pr-health": typeof import("./app/routes/pr-health.tsx");
};