import { useBusFactor } from '../hooks/useBusFactor';
import BusFactorTable from '../components/BusFactorTable';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/bus-factor";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Bus Factor - Workers SDK Dashboard" },
    { name: "description", content: "Code ownership analysis for cloudflare/workers-sdk" },
  ];
}

export default function BusFactor() {
  const { data, teamMembers, loading, error, lastUpdated, cached, refresh } = useBusFactor();

  return (
    <div className="view-container">
      <div className="page-header">
        <h2>Bus Factor Analysis</h2>
        <p className="subtitle">
          Analyze code ownership and knowledge distribution across critical directories.
        </p>
      </div>

      <BusFactorTable
        data={data}
        teamMembers={teamMembers}
        loading={loading}
        error={error}
        lastUpdated={lastUpdated}
        onRefresh={refresh}
      />

      <div className="view-footer">
        {cached && (
          <p className="note">Using cached data. Results are refreshed hourly.</p>
        )}
        <p>
          Analyzes the last 6 months of commits in monitored directories.
        </p>
        <p>
          <button onClick={refresh} className="sync-button" disabled={loading}>
            {loading ? 'Analyzing...' : 'Refresh Analysis'}
          </button>
        </p>
      </div>
    </div>
  );
}
