import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router';
import { useBusFactor } from '../hooks/useBusFactor';
import BusFactorTable from '../components/BusFactorTable';
import BusFactorByUserTable from '../components/BusFactorByUserTable';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/bus-factor";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Bus Factor - Workers SDK Dashboard" },
    { name: "description", content: "Code ownership analysis for cloudflare/workers-sdk" },
  ];
}

export default function BusFactor() {
  const [searchParams, setSearchParams] = useSearchParams();
  const { data, teamMembers, loading, refreshing, error, lastUpdated, cached, refresh } = useBusFactor();

  // Initialize view from URL params or default to 'directory'
  const [view, setView] = useState<'directory' | 'user'>(() => {
    const urlView = searchParams.get('view');
    return (urlView === 'directory' || urlView === 'user') ? urlView : 'directory';
  });

  // Update URL when view changes
  useEffect(() => {
    const newParams = new URLSearchParams(searchParams);
    newParams.set('view', view);
    setSearchParams(newParams, { replace: true });
  }, [view, searchParams, setSearchParams]);

  const handleViewChange = (newView: 'directory' | 'user') => {
    setView(newView);
  };

  return (
    <div className="view-container">
      <div className="page-header">
        <h2>Bus Factor Analysis</h2>
        <p className="subtitle">
          Analyze code ownership and knowledge distribution across critical directories.
        </p>
      </div>

      <div className="controls-bar">
        <div className="view-toggle">
          <button
            onClick={() => handleViewChange('directory')}
            className={view === 'directory' ? 'active' : ''}
          >
            By Directory
          </button>
          <button
            onClick={() => handleViewChange('user')}
            className={view === 'user' ? 'active' : ''}
          >
            By User
          </button>
        </div>
      </div>

      {view === 'directory' ? (
        <BusFactorTable
          data={data}
          teamMembers={teamMembers}
          loading={loading}
          error={error}
          lastUpdated={lastUpdated}
          onRefresh={refresh}
        />
      ) : (
        <BusFactorByUserTable
          data={data}
          teamMembers={teamMembers}
          loading={loading}
          error={error}
          lastUpdated={lastUpdated}
          onRefresh={refresh}
        />
      )}

      <div className="view-footer">
        {refreshing && (
          <p className="note refreshing-note">
            <span className="refreshing-indicator"></span>
            Refreshing data in background...
          </p>
        )}
        {cached && !refreshing && (
          <p className="note">Using cached data. Results are refreshed hourly.</p>
        )}
        <p>
          Analyzes all commits in monitored directories.
        </p>
        <p>
          <button onClick={refresh} className="sync-button" disabled={loading || refreshing}>
            {loading ? 'Analyzing...' : refreshing ? 'Refreshing...' : 'Refresh Analysis'}
          </button>
        </p>
      </div>
    </div>
  );
}
