import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router';
import { useCIData } from '../hooks/useCIData';
import Header from '../components/Header';
import JobFailureRatesView from '../components/JobFailureRatesView';
import HistoricalChartView from '../components/HistoricalChartView';
import DateRangeControls from '../components/DateRangeControls';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/ci-flakes";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "CI Flakes - Workers SDK Dashboard" },
    { name: "description", content: "CI health dashboard for cloudflare/workers-sdk changeset-release/main branch" },
  ];
}

export default function CIFlakes() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [runLimit] = useState(100);

  // Initialize date range from URL params or default to last 7 days
  const [dateRange, setDateRange] = useState<{ start: string; end: string }>(() => {
    const urlStart = searchParams.get('start');
    const urlEnd = searchParams.get('end');

    if (urlStart && urlEnd) {
      return { start: urlStart, end: urlEnd };
    }

    const end = new Date();
    const start = new Date();
    start.setDate(start.getDate() - 7); // Default: last 7 days
    return {
      start: start.toISOString().split('T')[0],
      end: end.toISOString().split('T')[0]
    };
  });

  // Initialize view from URL params or default to table
  const [view, setView] = useState<'table' | 'chart'>(() => {
    const urlView = searchParams.get('view');
    return (urlView === 'chart' || urlView === 'table') ? urlView : 'table';
  });

  const { data, loading, error, lastUpdated } = useCIData(runLimit, dateRange);

  // Update URL when date range changes
  useEffect(() => {
    const newParams = new URLSearchParams(searchParams);
    newParams.set('start', dateRange.start);
    newParams.set('end', dateRange.end);
    newParams.set('view', view);
    setSearchParams(newParams, { replace: true });
  }, [dateRange, view]);

  const handleDateRangeChange = (start: string, end: string) => {
    setDateRange({ start, end });
  };

  const handleViewChange = (newView: 'table' | 'chart') => {
    setView(newView);
  };

  return (
    <div className="view-container">
      <div className="page-header">
        <h2>CI Flakes</h2>
        <p className="subtitle">
          Monitoring CI jobs that run on Version Packages PRs. These jobs should never fail.
        </p>
      </div>

      <DateRangeControls
        dateRange={dateRange}
        onDateRangeChange={handleDateRangeChange}
        showViewToggle={true}
        view={view}
        onViewChange={handleViewChange}
      />

      {error && (
        <div className="error-message">
          Failed to load data: {error}. Please try again.
        </div>
      )}

      {data && data.jobStats && (
        <div className="overall-stats">
          {(() => {
            const jobs = Object.values(data.jobStats);
            const totalFailures = jobs.reduce((sum, job: any) => sum + job.failures, 0);
            const totalSuccesses = jobs.reduce((sum, job: any) => sum + job.successes, 0);
            const totalRuns = totalFailures + totalSuccesses;
            const overallFailureRate = totalRuns > 0 ? (totalFailures / totalRuns) * 100 : 0;

            return (
              <>
                <span className={`overall-rate ${overallFailureRate === 0 ? 'success' : overallFailureRate < 5 ? 'warning' : 'danger'}`}>
                  {overallFailureRate.toFixed(1)}% failure rate
                </span>
                <span className="overall-detail">
                  {totalFailures} failures / {totalSuccesses} successes / {totalRuns} total runs across {jobs.length} job types
                </span>
              </>
            );
          })()}
        </div>
      )}

      {view === 'table' ? (
        <JobFailureRatesView data={data} loading={loading} />
      ) : (
        <HistoricalChartView dateRange={dateRange} />
      )}

      <div className="view-footer">
        <Header
          loading={loading}
          lastUpdated={lastUpdated}
        />
        <p>Data sourced from GitHub Actions API | Branch: changeset-release/main</p>
      </div>
    </div>
  );
}
