import { redirect } from 'react-router';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/home";

export function loader({}: Route.LoaderArgs) {
  return redirect('/ci-flakes');
}

export default function Home() {
  // This should never render due to the redirect
  return null;
}
