import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router';
import { useCIData } from '../hooks/useCIData';
import Header from '../components/Header';
import JobFailureRatesView from '../components/JobFailureRatesView';
import HistoricalChartView from '../components/HistoricalChartView';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/home";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Workers SDK CI Analyzer - changeset-release/main" },
    { name: "description", content: "CI health dashboard for cloudflare/workers-sdk changeset-release/main branch" },
  ];
}

export default function Home({ params }: Route.ComponentProps) {
  const [searchParams, setSearchParams] = useSearchParams();
  const [runLimit] = useState(100);
  
  // Initialize date range from URL params or default to last 7 days
  const [dateRange, setDateRange] = useState<{ start: string; end: string }>(() => {
    const urlStart = searchParams.get('start');
    const urlEnd = searchParams.get('end');
    
    if (urlStart && urlEnd) {
      return { start: urlStart, end: urlEnd };
    }
    
    const end = new Date();
    const start = new Date();
    start.setDate(start.getDate() - 7); // Default: last 7 days
    return {
      start: start.toISOString().split('T')[0],
      end: end.toISOString().split('T')[0]
    };
  });
  
  // Initialize view from URL params or default to table
  const [view, setView] = useState<'table' | 'chart'>(() => {
    const urlView = searchParams.get('view');
    return (urlView === 'chart' || urlView === 'table') ? urlView : 'table';
  });
  
  const { data, loading, error, lastUpdated } = useCIData(runLimit, dateRange);
  
  // Update URL when date range changes
  useEffect(() => {
    const newParams = new URLSearchParams(searchParams);
    newParams.set('start', dateRange.start);
    newParams.set('end', dateRange.end);
    newParams.set('view', view);
    setSearchParams(newParams, { replace: true });
  }, [dateRange, view]);
  
  const handleDateRangeChange = (start: string, end: string) => {
    setDateRange({ start, end });
  };
  
  const handlePresetRange = (days: number) => {
    const end = new Date();
    const start = new Date();
    start.setDate(start.getDate() - days);
    setDateRange({
      start: start.toISOString().split('T')[0],
      end: end.toISOString().split('T')[0]
    });
  };
  
  const handleViewChange = (newView: 'table' | 'chart') => {
    setView(newView);
  };

  return (
    <div className="container">
      <main>
        <div className="page-header">
          <h1>changeset-release/main CI Health</h1>
          <p className="subtitle">
            Monitoring CI jobs that run on Version Packages PRs. These jobs should never fail.
          </p>
        </div>

        <div className="controls-bar">
          <div className="date-range-controls">
            <label>Date Range:</label>
            <div className="preset-buttons">
              <button 
                onClick={() => handlePresetRange(7)}
                className={dateRange.start === new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] ? 'active' : ''}
              >
                Last 7 Days
              </button>
              <button onClick={() => handlePresetRange(30)}>Last 30 Days</button>
              <button onClick={() => handlePresetRange(90)}>Last 90 Days</button>
              <button onClick={() => handlePresetRange(180)}>Last 6 Months</button>
            </div>
            <div className="custom-range">
              <input 
                type="date" 
                value={dateRange.start} 
                onChange={(e) => handleDateRangeChange(e.target.value, dateRange.end)}
                max={dateRange.end}
              />
              <span>to</span>
              <input 
                type="date" 
                value={dateRange.end} 
                onChange={(e) => handleDateRangeChange(dateRange.start, e.target.value)}
                min={dateRange.start}
                max={new Date().toISOString().split('T')[0]}
              />
            </div>
          </div>
          
          <div className="view-toggle">
            <button 
              onClick={() => handleViewChange('table')}
              className={view === 'table' ? 'active' : ''}
            >
              Table View
            </button>
            <button 
              onClick={() => handleViewChange('chart')}
              className={view === 'chart' ? 'active' : ''}
            >
              Chart View
            </button>
          </div>
        </div>

        {error && (
          <div className="error-message">
            Failed to load data: {error}. Please try again.
          </div>
        )}

        {view === 'table' ? (
          <JobFailureRatesView data={data} loading={loading} />
        ) : (
          <HistoricalChartView dateRange={dateRange} />
        )}
      </main>

      <footer>
        <Header
          loading={loading}
          lastUpdated={lastUpdated}
        />
        <p>Data sourced from GitHub Actions API • Branch: changeset-release/main</p>
      </footer>
    </div>
  );
}
