import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router';
import { useGitHubItems } from '../hooks/useGitHubItems';
import DateRangeControls from '../components/DateRangeControls';
import OpenItemsChart from '../components/OpenItemsChart';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/issues";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Issues - Workers SDK Dashboard" },
    { name: "description", content: "Open issues history for cloudflare/workers-sdk" },
  ];
}

export default function Issues() {
  const [searchParams, setSearchParams] = useSearchParams();

  // Initialize date range from URL params or default to last 6 months
  const [dateRange, setDateRange] = useState<{ start: string; end: string }>(() => {
    const urlStart = searchParams.get('start');
    const urlEnd = searchParams.get('end');

    if (urlStart && urlEnd) {
      return { start: urlStart, end: urlEnd };
    }

    const end = new Date();
    const start = new Date();
    start.setMonth(start.getMonth() - 6); // Default: last 6 months
    return {
      start: start.toISOString().split('T')[0],
      end: end.toISOString().split('T')[0]
    };
  });

  const { data, loading, error, totalItems, oldestDate, lastSync, needsSync } = useGitHubItems('issues', dateRange);

  // Update URL when date range changes
  useEffect(() => {
    const newParams = new URLSearchParams(searchParams);
    newParams.set('start', dateRange.start);
    newParams.set('end', dateRange.end);
    setSearchParams(newParams, { replace: true });
  }, [dateRange]);

  const handleDateRangeChange = (start: string, end: string) => {
    setDateRange({ start, end });
  };

  const handleSync = async (force: boolean = false) => {
    try {
      const url = force ? '/api/sync-github-items?force' : '/api/sync-github-items';
      const response = await fetch(url, { method: 'POST' });
      const result = await response.json();
      if (result.success) {
        // Refresh the data
        window.location.reload();
      } else {
        alert(`Sync failed: ${result.error}`);
      }
    } catch (err) {
      alert(`Sync failed: ${err}`);
    }
  };

  return (
    <div className="view-container">
      <div className="page-header">
        <h2>Issues</h2>
        <p className="subtitle">
          Tracking open issues in cloudflare/workers-sdk over time.
        </p>
      </div>

      {needsSync && (
        <div className="sync-banner">
          <p>No data available. The GitHub issues data needs to be synced.</p>
          <button onClick={() => handleSync(true)} className="sync-button">
            Sync Now
          </button>
        </div>
      )}

      <DateRangeControls
        dateRange={dateRange}
        onDateRangeChange={handleDateRangeChange}
        minDate={oldestDate || undefined}
      />

      <OpenItemsChart
        data={data}
        title="Issues"
        lineColor="rgb(59, 130, 246)" // Blue
        loading={loading}
        error={needsSync ? null : error}
        dateRange={dateRange}
      />

      <div className="view-footer">
        {lastSync && (
          <p className="last-updated">
            Last synced: {new Date(lastSync).toLocaleString()}
          </p>
        )}
        {totalItems > 0 && (
          <p>Total issues in database: {totalItems.toLocaleString()}</p>
        )}
        {oldestDate && (
          <p>Data available from: {oldestDate}</p>
        )}
        <p>Data sourced from GitHub GraphQL API (cached in KV)</p>
      </div>
    </div>
  );
}
