import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router';
import { useGitHubItems } from '../hooks/useGitHubItems';
import { useIssueLabelStats } from '../hooks/useIssueLabelStats';
import OpenItemsChart from '../components/OpenItemsChart';
import IssueLabelChart from '../components/IssueLabelChart';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/issues";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Issues - Workers SDK Dashboard" },
    { name: "description", content: "Open issues history for cloudflare/workers-sdk" },
  ];
}

export default function Issues() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [syncing, setSyncing] = useState(false);
  const [syncMessage, setSyncMessage] = useState<string | null>(null);

  // Initialize view from URL params or default to 'total'
  const [view, setView] = useState<'total' | 'by-label'>(() => {
    const urlView = searchParams.get('view');
    return (urlView === 'total' || urlView === 'by-label') ? urlView : 'total';
  });

  // Initialize date range from URL params or default to last 6 months
  const [dateRange, setDateRange] = useState<{ start: string; end: string }>(() => {
    const urlStart = searchParams.get('start');
    const urlEnd = searchParams.get('end');

    if (urlStart && urlEnd) {
      return { start: urlStart, end: urlEnd };
    }

    const end = new Date();
    const start = new Date();
    start.setMonth(start.getMonth() - 6); // Default: last 6 months
    return {
      start: start.toISOString().split('T')[0],
      end: end.toISOString().split('T')[0]
    };
  });

  // Data for "Total" view
  const { 
    data: totalData, 
    loading: totalLoading, 
    error: totalError, 
    totalItems, 
    oldestDate, 
    lastSync, 
    needsSync 
  } = useGitHubItems('issues', dateRange);

  // Data for "By Label" view
  const { 
    data: labelData, 
    loading: labelLoading, 
    error: labelError, 
    refetch: refetchLabels 
  } = useIssueLabelStats(dateRange);

  // Update URL when date range or view changes
  useEffect(() => {
    const newParams = new URLSearchParams(searchParams);
    newParams.set('start', dateRange.start);
    newParams.set('end', dateRange.end);
    newParams.set('view', view);
    setSearchParams(newParams, { replace: true });
  }, [dateRange, view, searchParams, setSearchParams]);

  const handleDateRangeChange = (start: string, end: string) => {
    setDateRange({ start, end });
  };

  const handleViewChange = (newView: 'total' | 'by-label') => {
    setView(newView);
  };

  const handleSync = async () => {
    setSyncing(true);
    setSyncMessage(null);
    
    try {
      const response = await fetch('/api/sync-github-items', { method: 'POST' });
      const result = await response.json() as { success?: boolean; error?: string; newItems?: number; updatedItems?: number };
      
      if (result.success) {
        setSyncMessage(`Sync complete! ${result.newItems} new, ${result.updatedItems} updated items.`);
        setTimeout(() => {
          window.location.reload();
        }, 1500);
      } else {
        setSyncMessage(`Sync failed: ${result.error}`);
      }
    } catch (err) {
      setSyncMessage(`Sync failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
    } finally {
      setSyncing(false);
    }
  };

  const loading = view === 'total' ? totalLoading : labelLoading;
  const error = view === 'total' ? totalError : labelError;

  return (
    <div className="view-container">
      <div className="page-header">
        <h2>Issues</h2>
        <p className="subtitle">
          {view === 'total' 
            ? 'Tracking open issues in cloudflare/workers-sdk over time.'
            : 'Track how issue counts change over time, broken down by label.'}
        </p>
      </div>

      {needsSync && (
        <div className="sync-banner">
          <p>No data available. The GitHub issues data needs to be synced.</p>
          <button onClick={handleSync} className="sync-button" disabled={syncing}>
            {syncing ? 'Syncing...' : 'Sync Now'}
          </button>
        </div>
      )}

      <div className="controls-bar">
        <div className="date-range-controls">
          <label>Date Range:</label>
          <div className="preset-buttons">
            <button onClick={() => handleDateRangeChange(
              new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
              new Date().toISOString().split('T')[0]
            )}>Last 7 Days</button>
            <button onClick={() => handleDateRangeChange(
              new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
              new Date().toISOString().split('T')[0]
            )}>Last 30 Days</button>
            <button onClick={() => handleDateRangeChange(
              new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
              new Date().toISOString().split('T')[0]
            )}>Last 90 Days</button>
            <button onClick={() => handleDateRangeChange(
              new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
              new Date().toISOString().split('T')[0]
            )}>Last 6 Months</button>
            <button onClick={() => handleDateRangeChange(
              new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
              new Date().toISOString().split('T')[0]
            )}>Last Year</button>
            {oldestDate && (
              <button onClick={() => handleDateRangeChange(
                oldestDate,
                new Date().toISOString().split('T')[0]
              )}>All Time</button>
            )}
          </div>
          <div className="custom-range">
            <input
              type="date"
              value={dateRange.start}
              onChange={(e) => handleDateRangeChange(e.target.value, dateRange.end)}
              min={oldestDate || undefined}
              max={dateRange.end}
            />
            <span>to</span>
            <input
              type="date"
              value={dateRange.end}
              onChange={(e) => handleDateRangeChange(dateRange.start, e.target.value)}
              min={dateRange.start}
              max={new Date().toISOString().split('T')[0]}
            />
          </div>
        </div>
        <div className="view-toggle">
          <button
            onClick={() => handleViewChange('total')}
            className={view === 'total' ? 'active' : ''}
          >
            Total
          </button>
          <button
            onClick={() => handleViewChange('by-label')}
            className={view === 'by-label' ? 'active' : ''}
          >
            By Label
          </button>
        </div>
      </div>

      {view === 'total' ? (
        <OpenItemsChart
          data={totalData}
          title="Issues"
          lineColor="rgb(59, 130, 246)"
          loading={totalLoading}
          error={needsSync ? null : totalError}
          dateRange={dateRange}
        />
      ) : (
        <IssueLabelChart
          data={labelData || { timestamps: [], total: [], labels: {} }}
          loading={labelLoading}
          error={labelError}
        />
      )}

      <div className="view-footer">
        {syncMessage && (
          <p className={syncMessage.includes('failed') ? 'error-text' : 'success-text'}>
            {syncMessage}
          </p>
        )}
        
        {lastSync && (
          <p className="last-updated">
            Last synced: {new Date(lastSync).toLocaleString()}
          </p>
        )}
        {view === 'total' && totalItems > 0 && (
          <p>Total issues in database: {totalItems.toLocaleString()}</p>
        )}
        {oldestDate && (
          <p>Data available from: {oldestDate}</p>
        )}
        
        <div className="footer-buttons">
          {view === 'by-label' && (
            <button 
              onClick={() => refetchLabels()} 
              className="sync-button secondary" 
              disabled={loading || syncing}
            >
              {labelLoading ? 'Loading...' : 'Refresh Chart'}
            </button>
          )}
          <button 
            onClick={handleSync} 
            className="sync-button" 
            disabled={loading || syncing}
          >
            {syncing ? 'Syncing GitHub Data...' : 'Sync GitHub Data'}
          </button>
        </div>
        
        <p className="note">Data sourced from GitHub API (cached in KV)</p>
      </div>
    </div>
  );
}
