import { useState } from 'react';
import { useIssueTriage, type TriageStats } from '../hooks/useIssueTriage';
import IssueTriageList from '../components/IssueTriageList';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/issue-triage";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Issue Triage - Workers SDK Dashboard" },
    { name: "description", content: "Issues needing triage attention for cloudflare/workers-sdk" },
  ];
}

type TabType = 'untriaged' | 'awaiting-dev' | 'awaiting-cf';

export default function IssueTriage() {
  const [activeTab, setActiveTab] = useState<TabType>('untriaged');
  const { 
    untriaged, 
    awaitingDev,
    awaitingCF,
    totalUntriaged,
    totalAwaitingDev,
    totalAwaitingCF,
    stats,
    lastSync,
    loading, 
    error,
    needsSync,
    refetch 
  } = useIssueTriage();
  
  // Get stats for active tab
  const getActiveStats = (): TriageStats => {
    switch (activeTab) {
      case 'untriaged': return stats.untriaged;
      case 'awaiting-dev': return stats.awaitingDev;
      case 'awaiting-cf': return stats.awaitingCF;
    }
  };
  
  const getActiveTotal = (): number => {
    switch (activeTab) {
      case 'untriaged': return totalUntriaged;
      case 'awaiting-dev': return totalAwaitingDev;
      case 'awaiting-cf': return totalAwaitingCF;
    }
  };

  const [syncing, setSyncing] = useState(false);
  const [syncMessage, setSyncMessage] = useState<string | null>(null);

  const handleSync = async () => {
    setSyncing(true);
    setSyncMessage(null);
    
    try {
      const response = await fetch('/api/sync-github-items', { method: 'POST' });
      const result = await response.json() as { success: boolean; newItems?: number; updatedItems?: number; error?: string };
      
      if (result.success) {
        setSyncMessage(`Sync complete! ${result.newItems} new, ${result.updatedItems} updated items.`);
        setTimeout(() => {
          refetch();
          setSyncMessage(null);
        }, 1500);
      } else {
        setSyncMessage(`Sync failed: ${result.error}`);
      }
    } catch (err) {
      setSyncMessage(`Sync failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
    } finally {
      setSyncing(false);
    }
  };

  if (loading) {
    return (
      <div className="view-container">
        <div className="loading-container">
          <div className="loading-spinner"></div>
          <p>Loading issue triage data...</p>
        </div>
      </div>
    );
  }

  if (error || needsSync) {
    return (
      <div className="view-container">
        <div className="page-header">
          <h2>Issue Triage</h2>
        </div>
        <div className="error-message">
          <p>{error || 'Data needs to be synced'}</p>
          <button onClick={handleSync} className="sync-button" disabled={syncing}>
            {syncing ? 'Syncing...' : 'Sync GitHub Data'}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="view-container">
      <div className="page-header">
        <h2>Issue Triage</h2>
        <p className="subtitle">
          Issues needing attention, filtered by triage status.
        </p>
      </div>

      <div className="triage-tabs">
        <button
          onClick={() => setActiveTab('untriaged')}
          className={`triage-tab ${activeTab === 'untriaged' ? 'active' : ''}`}
        >
          Untriaged
          <span className="triage-tab-count">{totalUntriaged}</span>
        </button>
        <button
          onClick={() => setActiveTab('awaiting-dev')}
          className={`triage-tab ${activeTab === 'awaiting-dev' ? 'active' : ''}`}
        >
          Awaiting Dev
          <span className="triage-tab-count">{totalAwaitingDev}</span>
        </button>
        <button
          onClick={() => setActiveTab('awaiting-cf')}
          className={`triage-tab ${activeTab === 'awaiting-cf' ? 'active' : ''}`}
        >
          Awaiting CF
          <span className="triage-tab-count">{totalAwaitingCF}</span>
        </button>
      </div>

      <div className="triage-description">
        {activeTab === 'untriaged' && (
          <p>
            Issues with "Untriaged" project status and no blocking labels. These need initial triage.
          </p>
        )}
        {activeTab === 'awaiting-dev' && (
          <p>
            Issues with "awaiting reporter response", "needs reproduction", or similar labels.
            These may need follow-up action.
          </p>
        )}
        {activeTab === 'awaiting-cf' && (
          <p>
            Issues with "awaiting Cloudflare response" label. These are waiting for internal 
            Cloudflare teams to provide information or fixes.
          </p>
        )}
      </div>

      {/* Stats Cards */}
      <div className="triage-stats">
        <div className="stat-card">
          <span className="stat-value">{getActiveTotal()}</span>
          <span className="stat-label">Issues</span>
        </div>
        <div className="stat-card">
          <span className="stat-value">{getActiveStats().avgAgeDays}</span>
          <span className="stat-label">Avg Age (days)</span>
        </div>
        <div className="stat-card">
          <span className="stat-value">{getActiveStats().avgStaleDays}</span>
          <span className="stat-label">Avg Stale (days)</span>
        </div>
        <div className="stat-card warning">
          <span className="stat-value">{getActiveStats().staleCount}</span>
          <span className="stat-label">Stale (&gt;14 days)</span>
        </div>
        <div className="stat-card critical">
          <span className="stat-value">{getActiveStats().veryStaleCount}</span>
          <span className="stat-label">Very Stale (&gt;30 days)</span>
        </div>
      </div>

      <div className="triage-content">
        {activeTab === 'untriaged' && (
          <IssueTriageList 
            issues={untriaged} 
            emptyMessage="No untriaged issues found."
          />
        )}
        {activeTab === 'awaiting-dev' && (
          <IssueTriageList 
            issues={awaitingDev} 
            emptyMessage="No issues awaiting dev attention."
          />
        )}
        {activeTab === 'awaiting-cf' && (
          <IssueTriageList 
            issues={awaitingCF} 
            emptyMessage="No issues awaiting Cloudflare response."
          />
        )}
      </div>

      <div className="view-footer">
        {syncMessage && (
          <p className={syncMessage.includes('failed') ? 'error-text' : 'success-text'}>
            {syncMessage}
          </p>
        )}
        
        {lastSync && (
          <p className="note">
            Last synced: {new Date(lastSync).toLocaleString()}
          </p>
        )}
        
        <div className="footer-buttons">
          <button 
            onClick={() => refetch()} 
            className="sync-button secondary" 
            disabled={loading || syncing}
          >
            {loading ? 'Loading...' : 'Refresh'}
          </button>
          <button 
            onClick={handleSync} 
            className="sync-button" 
            disabled={loading || syncing}
          >
            {syncing ? 'Syncing GitHub Data...' : 'Sync GitHub Data'}
          </button>
        </div>
      </div>
    </div>
  );
}
