import MainLayout from '../components/MainLayout';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/layout";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Workers SDK Dashboard" },
    { name: "description", content: "Dashboard for cloudflare/workers-sdk repository" },
  ];
}

export default function Layout() {
  return <MainLayout />;
}
