import { useState } from 'react';
import { usePRHealth, type SortKey, type SortOrder } from '../hooks/usePRHealth';
import PRHealthTable from '../components/PRHealthTable';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/pr-health";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "PR Health - Workers SDK Dashboard" },
    { name: "description", content: "Pull request health and staleness metrics for cloudflare/workers-sdk" },
  ];
}

export default function PRHealth() {
  const [stateFilter, setStateFilter] = useState<'open' | 'all'>('open');
  const [sortBy, setSortBy] = useState<SortKey>('stale');
  const [sortOrder, setSortOrder] = useState<SortOrder>('desc');

  const { 
    prs, 
    total,
    stats,
    lastSync,
    loading, 
    error,
    needsSync,
    refetch 
  } = usePRHealth(stateFilter, sortBy, sortOrder);

  const [syncing, setSyncing] = useState(false);
  const [syncMessage, setSyncMessage] = useState<string | null>(null);

  const handleSync = async () => {
    setSyncing(true);
    setSyncMessage(null);
    
    try {
      const response = await fetch('/api/sync-github-items', { method: 'POST' });
      const result = await response.json();
      
      if (result.success) {
        setSyncMessage(`Sync complete! ${result.newItems} new, ${result.updatedItems} updated items.`);
        setTimeout(() => {
          refetch();
          setSyncMessage(null);
        }, 1500);
      } else {
        setSyncMessage(`Sync failed: ${result.error}`);
      }
    } catch (err) {
      setSyncMessage(`Sync failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
    } finally {
      setSyncing(false);
    }
  };

  const handleSortChange = (key: SortKey) => {
    if (sortBy === key) {
      setSortOrder(sortOrder === 'desc' ? 'asc' : 'desc');
    } else {
      setSortBy(key);
      setSortOrder('desc');
    }
  };

  if (loading && prs.length === 0) {
    return (
      <div className="view-container">
        <div className="loading-container">
          <div className="loading-spinner"></div>
          <p>Loading PR health data...</p>
        </div>
      </div>
    );
  }

  if (error || needsSync) {
    return (
      <div className="view-container">
        <div className="page-header">
          <h2>PR Health</h2>
        </div>
        <div className="error-message">
          <p>{error || 'Data needs to be synced'}</p>
          <button onClick={handleSync} className="sync-button" disabled={syncing}>
            {syncing ? 'Syncing...' : 'Sync GitHub Data'}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="view-container">
      <div className="page-header">
        <h2>PR Health</h2>
        <p className="subtitle">
          Monitor pull request staleness, age, and activity.
        </p>
      </div>

      <div className="pr-health-controls">
        <div className="filter-group">
          <label>Show:</label>
          <select 
            value={stateFilter} 
            onChange={(e) => setStateFilter(e.target.value as 'open' | 'all')}
            className="filter-select"
          >
            <option value="open">Open PRs only</option>
            <option value="all">All PRs</option>
          </select>
        </div>
      </div>

      <PRHealthTable
        prs={prs}
        stats={stats}
        sortBy={sortBy}
        sortOrder={sortOrder}
        onSortChange={handleSortChange}
      />

      <div className="view-footer">
        {syncMessage && (
          <p className={syncMessage.includes('failed') ? 'error-text' : 'success-text'}>
            {syncMessage}
          </p>
        )}
        
        {lastSync && (
          <p className="note">
            Last synced: {new Date(lastSync).toLocaleString()}
          </p>
        )}
        
        <div className="footer-buttons">
          <button 
            onClick={() => refetch()} 
            className="sync-button secondary" 
            disabled={loading || syncing}
          >
            {loading ? 'Loading...' : 'Refresh'}
          </button>
          <button 
            onClick={handleSync} 
            className="sync-button" 
            disabled={loading || syncing}
          >
            {syncing ? 'Syncing GitHub Data...' : 'Sync GitHub Data'}
          </button>
        </div>
        
        <p className="note">
          Note: Comment counts require a fresh sync to populate.
        </p>
      </div>
    </div>
  );
}
