import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router';
import { usePRLabelStats } from '../hooks/usePRLabelStats';
import DateRangeControls from '../components/DateRangeControls';
import LabelChart from '../components/LabelChart';
// @ts-expect-error - generated by React Router
import type { Route } from "./+types/prs";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Pull Requests - Workers SDK Dashboard" },
    { name: "description", content: "PR trends by label for cloudflare/workers-sdk" },
  ];
}

export default function PullRequests() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [syncing, setSyncing] = useState(false);
  const [syncMessage, setSyncMessage] = useState<string | null>(null);

  // Initialize date range from URL params or default to last 30 days
  const [dateRange, setDateRange] = useState<{ start: string; end: string }>(() => {
    const urlStart = searchParams.get('start');
    const urlEnd = searchParams.get('end');

    if (urlStart && urlEnd) {
      return { start: urlStart, end: urlEnd };
    }

    const end = new Date();
    const start = new Date();
    start.setDate(start.getDate() - 30); // Default: last 30 days
    return {
      start: start.toISOString().split('T')[0],
      end: end.toISOString().split('T')[0]
    };
  });

  const { data, loading, error, refetch } = usePRLabelStats(dateRange);

  // Update URL when date range changes
  useEffect(() => {
    const newParams = new URLSearchParams(searchParams);
    newParams.set('start', dateRange.start);
    newParams.set('end', dateRange.end);
    setSearchParams(newParams, { replace: true });
  }, [dateRange, searchParams, setSearchParams]);

  const handleDateRangeChange = (start: string, end: string) => {
    setDateRange({ start, end });
  };

  const handleSync = async () => {
    setSyncing(true);
    setSyncMessage(null);
    
    try {
      const response = await fetch('/api/sync-github-items', { method: 'POST' });
      const result = await response.json() as { success?: boolean; error?: string; newItems?: number; updatedItems?: number };
      
      if (result.success) {
        setSyncMessage(`Sync complete! ${result.newItems} new, ${result.updatedItems} updated items.`);
        setTimeout(() => {
          refetch();
          setSyncMessage(null);
        }, 1500);
      } else {
        setSyncMessage(`Sync failed: ${result.error}`);
      }
    } catch (err) {
      setSyncMessage(`Sync failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
    } finally {
      setSyncing(false);
    }
  };

  return (
    <div className="view-container">
      <div className="page-header">
        <h2>Pull Requests</h2>
        <p className="subtitle">
          Track how PR counts change over time, broken down by label.
        </p>
      </div>

      <DateRangeControls
        dateRange={dateRange}
        onDateRangeChange={handleDateRangeChange}
      />

      <LabelChart
        data={data || { timestamps: [], total: [], labels: {} }}
        loading={loading}
        error={error}
        itemType="pr"
      />

      <div className="view-footer">
        {syncMessage && (
          <p className={syncMessage.includes('failed') ? 'error-text' : 'success-text'}>
            {syncMessage}
          </p>
        )}
        
        <div className="footer-buttons">
          <button 
            onClick={() => refetch()} 
            className="sync-button secondary" 
            disabled={loading || syncing}
          >
            {loading ? 'Loading...' : 'Refresh Chart'}
          </button>
          <button 
            onClick={handleSync} 
            className="sync-button" 
            disabled={loading || syncing}
          >
            {syncing ? 'Syncing GitHub Data...' : 'Sync GitHub Data'}
          </button>
        </div>
        
        <p className="note">
          Historical PR counts are computed from synced GitHub data.
        </p>
      </div>
    </div>
  );
}
